import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { describe, expect, it } from 'vitest';

import type { FormState, Mode } from '../../params/paramMetadata';
import { emitConfig } from '../emitConfig';

const HERE = dirname(fileURLToPath(import.meta.url));
const GOLDEN_DIR = join(HERE, 'golden');

const FIXED_VERSION = '1.0.0-test';
const FIXED_TIMESTAMP = new Date('2026-01-15T12:00:00.000Z');

function golden(name: string): string {
  return readFileSync(join(GOLDEN_DIR, name), 'utf8');
}

// Set REGEN_GOLDENS=1 to rewrite golden files from current emitter output
// instead of asserting against them. Use after an intentional rendering
// change, then re-run normally and inspect the diff.
const REGEN = process.env.REGEN_GOLDENS === '1';
function checkGolden(actual: string, name: string): void {
  if (REGEN) {
    writeFileSync(join(GOLDEN_DIR, name), actual);
    return;
  }
  expect(actual).toBe(golden(name));
}

interface MakeStateInput {
  readonly mode?: Mode;
  readonly values?: Record<string, unknown>;
}

function makeState(input: MakeStateInput = {}): FormState {
  const values = input.values ?? {};
  const touched: Record<string, boolean> = {};
  for (const k of Object.keys(values)) {
    touched[k] = true;
  }
  return {
    mode: input.mode ?? 'general',
    values,
    touched,
  };
}

function emit(state: FormState): string {
  return emitConfig(state, { version: FIXED_VERSION, timestamp: FIXED_TIMESTAMP });
}

describe('emitConfig — header + structure', () => {
  it('always includes the version, timestamp, and project URL', () => {
    const out = emit(makeState());
    expect(out).toContain('// nf-skyline-dia-ms configuration');
    expect(out).toContain(`v${FIXED_VERSION}`);
    expect(out).toContain('2026-01-15T12:00:00.000Z');
    expect(out).toContain('https://mriffle.github.io/nf-skyline-dia-ms-config-gui/');
  });

  it('ends with a trailing newline', () => {
    const out = emit(makeState({ values: { fasta: '/x.fasta' } }));
    expect(out.endsWith('\n')).toBe(true);
  });

  it('reads __APP_VERSION__ when no version override is supplied', () => {
    // We only assert the call returns a string; the value comes from
    // the Vite-injected global (or falls back to "0.0.0" in tests).
    const out = emitConfig(makeState(), { timestamp: FIXED_TIMESTAMP });
    expect(out).toMatch(/^\/\/ nf-skyline-dia-ms configuration\n/);
    expect(out).toMatch(/Generated by config-builder v\S+ on /);
  });
});

describe('emitConfig — golden files', () => {
  it('empty state -> only the alwaysEmit search_engine appears', () => {
    checkGolden(emit(makeState()), 'empty.config');
  });

  it('general / DIA-NN minimal', () => {
    const state = makeState({
      values: {
        quant_spectra_dir: { kind: 'single', path: '/data/wide' },
        search_engine: 'diann',
        spectral_library: '/lib.dlib',
        fasta: '/db.fasta',
      },
    });
    checkGolden(emit(state), 'general-diann-minimal.config');
  });

  it('general / EncyclopeDIA narrow + wide', () => {
    const state = makeState({
      values: {
        search_engine: 'encyclopedia',
        chromatogram_library_spectra_dir: '/data/narrow',
        quant_spectra_dir: { kind: 'single', path: '/data/wide' },
        fasta: '/db.fasta',
        spectral_library: '/lib.dlib',
      },
    });
    checkGolden(emit(state), 'general-encyclopedia-narrow-wide.config');
  });

  it('general / Cascadia nested block', () => {
    const state = makeState({
      values: {
        search_engine: 'cascadia',
        quant_spectra_dir: { kind: 'single', path: '/data/wide' },
        'cascadia.use_gpu': true,
        'cascadia.score_threshold': 0.85,
      },
    });
    checkGolden(emit(state), 'general-cascadia.config');
  });

  it('no-search mode emits bare null', () => {
    const state = makeState({ values: { search_engine: null } });
    checkGolden(emit(state), 'general-no-search.config');
  });

  it('batch-map quant_spectra_dir emits a Groovy Map literal', () => {
    const state = makeState({
      values: {
        quant_spectra_dir: {
          kind: 'batch-map',
          entries: [
            { name: 'PlateA', paths: ['/data/A'] },
            { name: 'PlateB', paths: ['/data/B'] },
            { name: 'PlateC', paths: ['/data/C'] },
          ],
        },
      },
    });
    checkGolden(emit(state), 'general-batch-map.config');
  });

  it('batch-map with multiple directories per batch emits a list value', () => {
    const state = makeState({
      values: {
        quant_spectra_dir: {
          kind: 'batch-map',
          entries: [
            { name: 'PlateA', paths: ['/data/A1', '/data/A2'] },
            // A single-path batch still emits a bare string, so mixed maps read naturally.
            { name: 'PlateB', paths: ['/data/B'] },
          ],
        },
      },
    });
    checkGolden(emit(state), 'general-batch-map-multidir.config');
  });

  it('trims surrounding whitespace from batch names', () => {
    const state = makeState({
      values: {
        quant_spectra_dir: {
          kind: 'batch-map',
          entries: [{ name: '  PlateA  ', paths: ['/data/A'] }],
        },
      },
    });
    expect(emit(state)).toContain("'PlateA': '/data/A'");
  });

  it('drops empty paths and batches left with no path at all', () => {
    const state = makeState({
      values: {
        quant_spectra_dir: {
          kind: 'batch-map',
          entries: [
            { name: 'PlateA', paths: ['/data/A', ''] },
            { name: 'Empty', paths: [''] },
          ],
        },
      },
    });
    const out = emit(state);
    expect(out).toContain("'PlateA': '/data/A'");
    expect(out).not.toContain('Empty');
  });

  it('PDC / DIA-NN simple', () => {
    const state = makeState({
      mode: 'pdc',
      values: {
        'pdc.study_id': 'PDC000504',
        'pdc.n_raw_files': 10,
        search_engine: 'diann',
        fasta: '/db.fasta',
      },
    });
    checkGolden(emit(state), 'pdc-diann-simple.config');
  });

  it('PDC + Carafe sample', () => {
    const state = makeState({
      mode: 'pdc',
      values: {
        'pdc.study_id': 'PDC000504',
        use_carafe: true,
        'carafe.source': 'pdc-sample',
        'carafe.pdc_n_files': 5,
        'carafe.include_phosphorylation': true,
      },
    });
    checkGolden(emit(state), 'pdc-carafe-sample.config');
  });

  it('msconvert-only with bool false', () => {
    const state = makeState({
      values: {
        msconvert_only: true,
        quant_spectra_dir: { kind: 'single', path: '/data/wide' },
        'msconvert.do_demultiplex': false,
      },
    });
    checkGolden(emit(state), 'msconvert-only.config');
  });

  it('escape edges (quotes and backslashes)', () => {
    const state = makeState({
      values: {
        'diann.fasta_digest_params': "--cut 'K*,R*,!*P' --bs\\path",
      },
    });
    checkGolden(emit(state), 'escape-edges.config');
  });

  it('percent-encodes URL values (Panorama) but leaves local paths alone', () => {
    const state = makeState({
      values: {
        search_engine: 'diann',
        // Local path with a space — must NOT be encoded.
        fasta: '/data/My Lab/db.fasta',
        // Panorama URL: space -> %20, "@" kept as-is.
        quant_spectra_dir: {
          kind: 'single',
          path: 'https://panoramaweb.org/_webdav/My Lab/@files/run a.raw',
        },
        // string-list: URL element encoded, local element untouched.
        'skyline.skyr_file': [
          'https://panoramaweb.org/_webdav/A B/report.skyr',
          '/local/A B/report.skyr',
        ],
        // Mixed input: typed space + already-encoded %40 -> single encoded form.
        'panorama.upload': true,
        'panorama.upload_url': 'https://panoramaweb.org/_webdav/My Lab/%40files/',
      },
    });
    checkGolden(emit(state), 'url-encoding.config');
  });

  it('preserved outer-scope content (blocks + directives) is appended verbatim after params { }', () => {
    const state: FormState = {
      mode: 'general',
      values: { fasta: '/db.fasta', search_engine: 'diann' },
      touched: { fasta: true, search_engine: true },
      preservedOuterText:
        "process {\n    cpus = 4\n    memory = '16 GB'\n}\n\nprofiles {\n    standard { process.executor = 'local' }\n    cluster  { process.executor = 'slurm' }\n}\n\nincludeConfig '/net/maccoss/includes/nextflow-dia.include'",
    };
    checkGolden(emit(state), 'preserved-outer-blocks.config');
  });
});

describe('emitConfig — generated standard profile', () => {
  it('always appends a standard profile with default resource limits', () => {
    const out = emit(makeState());
    expect(out).toContain('// Execution profile');
    expect(out).toContain('profiles {');
    expect(out).toContain('standard {');
    expect(out).toContain("process.executor = 'local'");
    expect(out).toContain(
      "process.resourceLimits = [ cpus: 8, memory: '12.GB', time: '240.h' ]",
    );
    expect(out).toContain("params.mzml_cache_directory = 'mzml_cache'");
    expect(out).toContain("params.panorama_cache_directory = 'raw_cache'");
  });

  it('reflects the resource/cache form fields in the profile', () => {
    const state = makeState({
      values: {
        max_cpus: 32,
        max_memory: '250.GB',
        max_time: '72.h',
        mzml_cache_directory: '/scratch/mzml',
        panorama_cache_directory: '/scratch/raw',
      },
    });
    const out = emit(state);
    expect(out).toContain(
      "process.resourceLimits = [ cpus: 32, memory: '250.GB', time: '72.h' ]",
    );
    expect(out).toContain("params.mzml_cache_directory = '/scratch/mzml'");
    expect(out).toContain("params.panorama_cache_directory = '/scratch/raw'");
  });

  it('never emits the resource/cache params inside params { }', () => {
    const state = makeState({ values: { max_cpus: 16, fasta: '/db.fasta' } });
    const out = emit(state);
    const paramsBlock = out.slice(out.indexOf('params {'), out.indexOf('// Execution profile'));
    expect(paramsBlock).not.toContain('max_cpus');
  });

  it('suppresses the generated profile when the upload already has a profiles block', () => {
    const state: FormState = {
      mode: 'general',
      values: { fasta: '/db.fasta' },
      touched: { fasta: true },
      preservedOuterText:
        "profiles {\n    cluster { process.executor = 'slurm' }\n}",
    };
    const out = emit(state);
    expect(out).not.toContain('// Execution profile');
    // The user's profiles block rides through under the preserved banner.
    expect(out).toContain('Preserved from uploaded config');
    expect(out).toContain("cluster { process.executor = 'slurm' }");
    // Exactly one profiles block in the output.
    expect(out.match(/profiles \{/g)?.length).toBe(1);
  });

  it('keeps an uploaded resource param in params { } when profiles are preserved (no silent drop)', () => {
    const state: FormState = {
      mode: 'general',
      values: { max_cpus: 16 },
      touched: { max_cpus: true },
      preservedOuterText: "profiles {\n    standard { x = 1 }\n}",
    };
    const out = emit(state);
    // Generated profile suppressed, but the value survives at top level.
    expect(out).not.toContain('// Execution profile');
    expect(out).toContain('max_cpus = 16');
  });

  it('still emits the generated profile when preserved content has no profiles block', () => {
    const state: FormState = {
      mode: 'general',
      values: { fasta: '/db.fasta' },
      touched: { fasta: true },
      preservedOuterText: "process {\n    cpus = 4\n}",
    };
    const out = emit(state);
    expect(out).toContain('// Execution profile');
    expect(out).toContain('profiles {');
    expect(out).toContain('Preserved from uploaded config');
    expect(out).toContain('cpus = 4');
  });
});

describe('emitConfig — virtual params are skipped', () => {
  it('a virtual paramMetadata path passed via touched is ignored', () => {
    // `use_carafe` is virtual: it should never appear in output.
    const state: FormState = {
      mode: 'general',
      values: { use_carafe: true, fasta: '/db.fasta' },
      touched: { use_carafe: true, fasta: true },
    };
    const out = emit(state);
    expect(out).not.toContain('use_carafe');
    expect(out).toContain("fasta = '/db.fasta'");
  });
});

describe('emitConfig — list form of quant_spectra_dir', () => {
  it('emits a list literal', () => {
    const state = makeState({
      values: {
        quant_spectra_dir: { kind: 'list', paths: ['/a', '/b'] },
      },
    });
    const out = emit(state);
    expect(out).toContain("quant_spectra_dir = ['/a', '/b']");
  });
});

describe('emitConfig — nested namespace collapse', () => {
  it('encyclopedia with one sub-branch child folds to dotted form inside its block', () => {
    // encyclopedia has 3 children: quant.params, chromatogram.params,
    // save_output. quant and chromatogram each have one child (params),
    // so they should collapse to dotted form INSIDE the encyclopedia
    // block. The block itself stays a block because it has 3 children
    // at the top level.
    const state = makeState({
      values: {
        'encyclopedia.quant.params': '--quant-flag',
        'encyclopedia.chromatogram.params': '--chrom-flag',
        'encyclopedia.save_output': false,
      },
    });
    const out = emit(state);
    expect(out).toContain('encyclopedia {');
    expect(out).toContain("    quant.params = '--quant-flag'");
    expect(out).toContain("    chromatogram.params = '--chrom-flag'");
    expect(out).toContain('    save_output = false');
    // Ensure dotted form is NOT a top-level dotted (which would be
    // encyclopedia.quant.params at level 1).
    expect(out).not.toContain('    encyclopedia.quant.params');
  });

  it('a single-child top-level branch collapses to a single dotted line', () => {
    const state = makeState({
      values: { 'cascadia.use_gpu': true },
    });
    const out = emit(state);
    expect(out).toContain('    cascadia.use_gpu = true');
    expect(out).not.toContain('cascadia {');
  });
});

describe('emitConfig — untouched values are skipped', () => {
  it('a value present in `values` but not marked touched is not emitted', () => {
    const state: FormState = {
      mode: 'general',
      values: { fasta: '/db.fasta', spectral_library: '/lib.dlib' },
      touched: { fasta: true }, // spectral_library is NOT touched
    };
    const out = emit(state);
    expect(out).toContain("fasta = '/db.fasta'");
    expect(out).not.toContain('spectral_library');
  });
});

describe('emitConfig — touched-but-empty values are skipped', () => {
  it('does not emit a scalar field the user cleared back to empty', () => {
    // Repro: type a value into an optional field, then erase it. The
    // path is still touched with value '' — it must NOT appear.
    const state: FormState = {
      mode: 'general',
      values: { chromatogram_library_spectra_dir: '' },
      touched: { chromatogram_library_spectra_dir: true },
    };
    const out = emit(state);
    expect(out).not.toContain('chromatogram_library_spectra_dir');
  });

  it('does not emit an empty list or empty quant_spectra_dir', () => {
    const state: FormState = {
      mode: 'general',
      values: {
        quant_spectra_dir: { kind: 'list', paths: [] },
        'carafe.pdc_files': [],
      },
      touched: { quant_spectra_dir: true, 'carafe.pdc_files': true },
    };
    const out = emit(state);
    expect(out).not.toContain('quant_spectra_dir');
    expect(out).not.toContain('pdc_files');
  });

  it('still emits real falsy values (false / 0)', () => {
    const state: FormState = {
      mode: 'general',
      values: { use_vendor_raw: false, files_per_quant_batch: 0 },
      touched: { use_vendor_raw: true, files_per_quant_batch: true },
    };
    const out = emit(state);
    expect(out).toContain('use_vendor_raw = false');
    expect(out).toContain('files_per_quant_batch = 0');
  });
});

describe('emitConfig — affects-only paths (no direct ParamMeta)', () => {
  // quant_spectra_glob et al. are reachable only via a virtual parent's
  // `affects` list. They must still be emitted when touched — section
  // and ordering inherit from the parent virtual.
  it('emits quant_spectra_glob in the general input section', () => {
    const state = makeState({
      values: { quant_spectra_glob: '*.mzML' },
    });
    const out = emit(state);
    expect(out).toContain("quant_spectra_glob = '*.mzML'");
    expect(out).toContain('Input data (general)');
  });

  it('emits chromatogram_library_spectra_glob alongside the general input section', () => {
    const state = makeState({
      values: { chromatogram_library_spectra_glob: '*.raw' },
    });
    const out = emit(state);
    expect(out).toContain("chromatogram_library_spectra_glob = '*.raw'");
  });

  it('emits carafe glob/regex paths when Carafe is configured', () => {
    const state = makeState({
      values: { 'carafe.spectra_glob': '*.d.zip' },
    });
    const out = emit(state);
    expect(out).toContain("carafe.spectra_glob = '*.d.zip'");
  });
});

describe('emitConfig — hidden / unmodeled preserved params', () => {
  // Touched paths that have no direct ParamMeta and no virtual-parent
  // fallback (typically hidden infra params like images.*) emit at the
  // end of params { } under a "Preserved from uploaded config" banner.
  it('renders images.* under the preserved sub-block at the end of params', () => {
    // images.proteowizard and images.encyclopedia remain hidden-only in the
    // UX overlay, so they exercise the preserved sub-block path. (images.diann
    // is now a surfaced ParamMeta entry and would route to the search section.)
    const state: FormState = {
      mode: 'general',
      values: {
        fasta: '/db.fasta',
        'images.proteowizard': 'quay.io/user/pwiz:custom',
        'images.encyclopedia': 'quay.io/user/encyclopedia:custom',
      },
      touched: {
        fasta: true,
        'images.proteowizard': true,
        'images.encyclopedia': true,
      },
    };
    const out = emit(state);
    expect(out).toContain("fasta = '/db.fasta'");
    expect(out).toContain('Preserved from uploaded config');
    expect(out).toContain("proteowizard = 'quay.io/user/pwiz:custom'");
    expect(out).toContain("encyclopedia = 'quay.io/user/encyclopedia:custom'");
    // Should namespace-collapse into an images { } block.
    expect(out).toContain('images {');
    // Preserved sub-block must come after the regular sections.
    expect(out.indexOf("fasta = '/db.fasta'")).toBeLessThan(
      out.indexOf('Preserved from uploaded config'),
    );
  });
});
