import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { describe, expect, it } from 'vitest';

import type { FormState, Mode } from '../../params/paramMetadata';
import { emitConfig } from '../emitConfig';

const HERE = dirname(fileURLToPath(import.meta.url));
const GOLDEN_DIR = join(HERE, 'golden');

const FIXED_VERSION = '1.0.0-test';
const FIXED_TIMESTAMP = new Date('2026-01-15T12:00:00.000Z');

function golden(name: string): string {
  return readFileSync(join(GOLDEN_DIR, name), 'utf8');
}

interface MakeStateInput {
  readonly mode?: Mode;
  readonly values?: Record<string, unknown>;
}

function makeState(input: MakeStateInput = {}): FormState {
  const values = input.values ?? {};
  const touched: Record<string, boolean> = {};
  for (const k of Object.keys(values)) {
    touched[k] = true;
  }
  return {
    mode: input.mode ?? 'general',
    values,
    touched,
  };
}

function emit(state: FormState): string {
  return emitConfig(state, { version: FIXED_VERSION, timestamp: FIXED_TIMESTAMP });
}

describe('emitConfig — header + structure', () => {
  it('always includes the version, timestamp, and project URL', () => {
    const out = emit(makeState());
    expect(out).toContain('// nf-skyline-dia-ms configuration');
    expect(out).toContain(`v${FIXED_VERSION}`);
    expect(out).toContain('2026-01-15T12:00:00.000Z');
    expect(out).toContain('https://mriffle.github.io/nf-skyline-dia-ms-config-gui/');
  });

  it('ends with a trailing newline', () => {
    const out = emit(makeState({ values: { fasta: '/x.fasta' } }));
    expect(out.endsWith('\n')).toBe(true);
  });

  it('reads __APP_VERSION__ when no version override is supplied', () => {
    // We only assert the call returns a string; the value comes from
    // the Vite-injected global (or falls back to "0.0.0" in tests).
    const out = emitConfig(makeState(), { timestamp: FIXED_TIMESTAMP });
    expect(out).toMatch(/^\/\/ nf-skyline-dia-ms configuration\n/);
    expect(out).toMatch(/Generated by config-builder v\S+ on /);
  });
});

describe('emitConfig — golden files', () => {
  it('empty state -> only the alwaysEmit search_engine appears', () => {
    expect(emit(makeState())).toBe(golden('empty.config'));
  });

  it('general / DIA-NN minimal', () => {
    const state = makeState({
      values: {
        quant_spectra_dir: { kind: 'single', path: '/data/wide' },
        search_engine: 'diann',
        spectral_library: '/lib.dlib',
        fasta: '/db.fasta',
      },
    });
    expect(emit(state)).toBe(golden('general-diann-minimal.config'));
  });

  it('general / EncyclopeDIA narrow + wide', () => {
    const state = makeState({
      values: {
        search_engine: 'encyclopedia',
        chromatogram_library_spectra_dir: '/data/narrow',
        quant_spectra_dir: { kind: 'single', path: '/data/wide' },
        fasta: '/db.fasta',
        spectral_library: '/lib.dlib',
      },
    });
    expect(emit(state)).toBe(golden('general-encyclopedia-narrow-wide.config'));
  });

  it('general / Cascadia nested block', () => {
    const state = makeState({
      values: {
        search_engine: 'cascadia',
        quant_spectra_dir: { kind: 'single', path: '/data/wide' },
        'cascadia.use_gpu': true,
        'cascadia.score_threshold': 0.85,
      },
    });
    expect(emit(state)).toBe(golden('general-cascadia.config'));
  });

  it('no-search mode emits bare null', () => {
    const state = makeState({ values: { search_engine: null } });
    expect(emit(state)).toBe(golden('general-no-search.config'));
  });

  it('batch-map quant_spectra_dir emits a Groovy Map literal', () => {
    const state = makeState({
      values: {
        quant_spectra_dir: {
          kind: 'batch-map',
          entries: [
            { name: 'PlateA', path: '/data/A' },
            { name: 'PlateB', path: '/data/B' },
            { name: 'PlateC', path: '/data/C' },
          ],
        },
      },
    });
    expect(emit(state)).toBe(golden('general-batch-map.config'));
  });

  it('PDC / DIA-NN simple', () => {
    const state = makeState({
      mode: 'pdc',
      values: {
        'pdc.study_id': 'PDC000504',
        'pdc.n_raw_files': 10,
        search_engine: 'diann',
        fasta: '/db.fasta',
      },
    });
    expect(emit(state)).toBe(golden('pdc-diann-simple.config'));
  });

  it('PDC + Carafe sample', () => {
    const state = makeState({
      mode: 'pdc',
      values: {
        'pdc.study_id': 'PDC000504',
        use_carafe: true,
        'carafe.source': 'pdc-sample',
        'carafe.pdc_n_files': 5,
        'carafe.include_phosphorylation': true,
      },
    });
    expect(emit(state)).toBe(golden('pdc-carafe-sample.config'));
  });

  it('msconvert-only with bool false', () => {
    const state = makeState({
      values: {
        msconvert_only: true,
        quant_spectra_dir: { kind: 'single', path: '/data/wide' },
        'msconvert.do_demultiplex': false,
      },
    });
    expect(emit(state)).toBe(golden('msconvert-only.config'));
  });

  it('escape edges (quotes and backslashes)', () => {
    const state = makeState({
      values: {
        'diann.fasta_digest_params': "--cut 'K*,R*,!*P' --bs\\path",
      },
    });
    expect(emit(state)).toBe(golden('escape-edges.config'));
  });

  it('preserved outer blocks are appended verbatim after params { }', () => {
    const state: FormState = {
      mode: 'general',
      values: { fasta: '/db.fasta', search_engine: 'diann' },
      touched: { fasta: true, search_engine: true },
      preservedOuterText:
        "process {\n    cpus = 4\n    memory = '16 GB'\n}\n\nprofiles {\n    standard { process.executor = 'local' }\n    cluster  { process.executor = 'slurm' }\n}",
    };
    expect(emit(state)).toBe(golden('preserved-outer-blocks.config'));
  });
});

describe('emitConfig — virtual params are skipped', () => {
  it('a virtual paramMetadata path passed via touched is ignored', () => {
    // `use_carafe` is virtual: it should never appear in output.
    const state: FormState = {
      mode: 'general',
      values: { use_carafe: true, fasta: '/db.fasta' },
      touched: { use_carafe: true, fasta: true },
    };
    const out = emit(state);
    expect(out).not.toContain('use_carafe');
    expect(out).toContain("fasta = '/db.fasta'");
  });
});

describe('emitConfig — list form of quant_spectra_dir', () => {
  it('emits a list literal', () => {
    const state = makeState({
      values: {
        quant_spectra_dir: { kind: 'list', paths: ['/a', '/b'] },
      },
    });
    const out = emit(state);
    expect(out).toContain("quant_spectra_dir = ['/a', '/b']");
  });
});

describe('emitConfig — nested namespace collapse', () => {
  it('encyclopedia with one sub-branch child folds to dotted form inside its block', () => {
    // encyclopedia has 3 children: quant.params, chromatogram.params,
    // save_output. quant and chromatogram each have one child (params),
    // so they should collapse to dotted form INSIDE the encyclopedia
    // block. The block itself stays a block because it has 3 children
    // at the top level.
    const state = makeState({
      values: {
        'encyclopedia.quant.params': '--quant-flag',
        'encyclopedia.chromatogram.params': '--chrom-flag',
        'encyclopedia.save_output': false,
      },
    });
    const out = emit(state);
    expect(out).toContain('encyclopedia {');
    expect(out).toContain("    quant.params = '--quant-flag'");
    expect(out).toContain("    chromatogram.params = '--chrom-flag'");
    expect(out).toContain('    save_output = false');
    // Ensure dotted form is NOT a top-level dotted (which would be
    // encyclopedia.quant.params at level 1).
    expect(out).not.toContain('    encyclopedia.quant.params');
  });

  it('a single-child top-level branch collapses to a single dotted line', () => {
    const state = makeState({
      values: { 'cascadia.use_gpu': true },
    });
    const out = emit(state);
    expect(out).toContain('    cascadia.use_gpu = true');
    expect(out).not.toContain('cascadia {');
  });
});

describe('emitConfig — untouched values are skipped', () => {
  it('a value present in `values` but not marked touched is not emitted', () => {
    const state: FormState = {
      mode: 'general',
      values: { fasta: '/db.fasta', spectral_library: '/lib.dlib' },
      touched: { fasta: true }, // spectral_library is NOT touched
    };
    const out = emit(state);
    expect(out).toContain("fasta = '/db.fasta'");
    expect(out).not.toContain('spectral_library');
  });
});

describe('emitConfig — affects-only paths (no direct ParamMeta)', () => {
  // quant_spectra_glob et al. are reachable only via a virtual parent's
  // `affects` list. They must still be emitted when touched — section
  // and ordering inherit from the parent virtual.
  it('emits quant_spectra_glob in the general input section', () => {
    const state = makeState({
      values: { quant_spectra_glob: '*.mzML' },
    });
    const out = emit(state);
    expect(out).toContain("quant_spectra_glob = '*.mzML'");
    expect(out).toContain('Input data (general)');
  });

  it('emits chromatogram_library_spectra_glob alongside the general input section', () => {
    const state = makeState({
      values: { chromatogram_library_spectra_glob: '*.raw' },
    });
    const out = emit(state);
    expect(out).toContain("chromatogram_library_spectra_glob = '*.raw'");
  });

  it('emits carafe glob/regex paths when Carafe is configured', () => {
    const state = makeState({
      values: { 'carafe.spectra_glob': '*.d.zip' },
    });
    const out = emit(state);
    expect(out).toContain("carafe.spectra_glob = '*.d.zip'");
  });
});

describe('emitConfig — hidden / unmodeled preserved params', () => {
  // Touched paths that have no direct ParamMeta and no virtual-parent
  // fallback (typically hidden infra params like images.*) emit at the
  // end of params { } under a "Preserved from uploaded config" banner.
  it('renders images.* under the preserved sub-block at the end of params', () => {
    const state: FormState = {
      mode: 'general',
      values: {
        fasta: '/db.fasta',
        'images.diann': 'quay.io/user/diann:custom',
        'images.proteowizard': 'quay.io/user/pwiz:custom',
      },
      touched: {
        fasta: true,
        'images.diann': true,
        'images.proteowizard': true,
      },
    };
    const out = emit(state);
    expect(out).toContain("fasta = '/db.fasta'");
    expect(out).toContain('Preserved from uploaded config');
    expect(out).toContain("diann = 'quay.io/user/diann:custom'");
    expect(out).toContain("proteowizard = 'quay.io/user/pwiz:custom'");
    // Should namespace-collapse into an images { } block.
    expect(out).toContain('images {');
    // Preserved sub-block must come after the regular sections.
    expect(out.indexOf("fasta = '/db.fasta'")).toBeLessThan(
      out.indexOf('Preserved from uploaded config'),
    );
  });
});
