import type { FormState } from '../../../params/paramMetadata';
import { useStore } from '../../../state/store';
import { useFormState } from '../../../hooks/useValidation';
import { Field } from '../../form/Field';
import { WizardRadioCards } from '../WizardRadioCards';

type Strategy = 'predict' | 'upload' | 'carafe';

function readEngine(state: FormState): 'diann' | 'encyclopedia' | 'cascadia' | null {
  const v = state.values['search_engine'];
  if (typeof v !== 'string') return null;
  const lower = v.toLowerCase();
  if (lower === 'diann') return 'diann';
  if (lower === 'encyclopedia') return 'encyclopedia';
  if (lower === 'cascadia') return 'cascadia';
  return null;
}

function isNonEmptyString(v: unknown): boolean {
  return typeof v === 'string' && v.trim().length > 0;
}

function readStrategy(
  state: FormState,
  engine: 'diann' | 'encyclopedia' | 'cascadia' | null,
): Strategy | null {
  if (state.values['use_carafe'] === true) return 'carafe';
  // Upload is identified by `touched` (not just a non-empty value) so the
  // selection sticks while the user is mid-edit of an empty library path.
  if (state.touched['spectral_library'] === true) return 'upload';
  // For DIA-NN, "predict from FASTA" is the only remaining option — make
  // that the implied selection so users get visual feedback after clicking
  // it (and after the initial use_carafe=true default is turned off).
  if (engine === 'diann') return 'predict';
  // EncyclopeDIA must explicitly upload or pick Carafe.
  return null;
}

export function LibraryStrategyScreen() {
  const state = useFormState();
  const setValue = useStore((s) => s.setValue);
  const clearValue = useStore((s) => s.clearValue);

  const engine = readEngine(state);
  const current = readStrategy(state, engine);

  const onChange = (next: Strategy): void => {
    if (next === 'predict') {
      setValue('use_carafe', false);
      clearValue('spectral_library');
    } else if (next === 'upload') {
      setValue('use_carafe', false);
      // Mark as touched but empty so the file-or-url widget shows. The user
      // fills the path via the field below.
      if (!isNonEmptyString(state.values['spectral_library'])) {
        setValue('spectral_library', '');
      }
    } else {
      setValue('use_carafe', true);
      clearValue('spectral_library');
    }
  };

  const options =
    engine === 'encyclopedia'
      ? ([
          {
            value: 'upload' as const,
            label: 'Upload my own library',
            description:
              'Provide a .blib, .dlib, or .elib file. EncyclopeDIA converts formats automatically when needed.',
          },
          {
            value: 'carafe' as const,
            label: 'Generate with Carafe',
            description:
              'Run Carafe before the search to build a custom library. You will pick its input spectra on the next screen.',
            note: 'Recommended',
          },
        ] as const)
      : ([
          {
            value: 'predict' as const,
            label: 'Predict from FASTA',
            description:
              'DIA-NN generates its own spectral library from the FASTA. No upload needed.',
          },
          {
            value: 'upload' as const,
            label: 'Upload my own library',
            description:
              'Provide a .blib, .dlib, .elib, or .tsv library. Converted automatically as needed.',
          },
          {
            value: 'carafe' as const,
            label: 'Generate with Carafe',
            description:
              'Run Carafe before the search to build a custom library. Overrides any uploaded library.',
            note: 'Recommended',
          },
        ] as const);

  return (
    <div className="space-y-4">
      <p className="text-sm text-slate-600">
        {engine === 'encyclopedia'
          ? 'EncyclopeDIA always needs a spectral library. Either provide one or let Carafe generate one.'
          : 'DIA-NN can predict its own library from the FASTA, accept a library you provide, or use one generated by Carafe.'}
      </p>
      <WizardRadioCards<Strategy>
        ariaLabel="Library strategy"
        value={current}
        onChange={onChange}
        options={options}
      />
      {current === 'upload' ? (
        <div className="rounded-md border border-slate-200 bg-slate-50 p-3">
          <Field path="spectral_library" />
        </div>
      ) : null}
    </div>
  );
}

export function libraryStrategyCanAdvance(state: FormState): boolean {
  const engine = readEngine(state);
  if (engine === 'cascadia') return true;
  const carafe = state.values['use_carafe'] === true;
  if (carafe) return true;
  const libSet = isNonEmptyString(state.values['spectral_library']);
  if (libSet) return true;
  // DIA-NN with predict-from-FASTA is valid; EncyclopeDIA requires a library
  // or Carafe.
  return engine === 'diann';
}
