import { useEffect } from 'react';
import type { FormState } from '../../../params/paramMetadata';
import { useStore } from '../../../state/store';
import { useFieldValue } from '../../../hooks/useFieldValue';
import { useFormState } from '../../../hooks/useValidation';
import { Field } from '../../form/Field';
import { WizardAdvancedSection } from '../WizardAdvancedSection';
import { WizardRadioCards } from '../WizardRadioCards';

type Engine = 'diann' | 'encyclopedia' | 'cascadia';

function readEngine(value: unknown): Engine | null {
  if (typeof value !== 'string') return null;
  const lower = value.toLowerCase();
  if (lower === 'diann') return 'diann';
  if (lower === 'encyclopedia') return 'encyclopedia';
  if (lower === 'cascadia') return 'cascadia';
  return null;
}

function quantSpectraKind(value: unknown): string | null {
  if (value === null || typeof value !== 'object') return null;
  const k = (value as { kind?: unknown }).kind;
  return typeof k === 'string' ? k : null;
}

function isDzipFormat(state: FormState): boolean {
  return state.values['quant_input_format'] === 'dzip';
}

function isLockedToDiann(state: FormState): {
  readonly locked: boolean;
  readonly reason?: string;
} {
  // .d.zip lock applies in both General and PDC: EncyclopeDIA and
  // Cascadia reject Bruker .d.zip at workflow validation.
  if (isDzipFormat(state)) {
    return {
      locked: true,
      reason:
        'Bruker .d.zip is only supported by DIA-NN. EncyclopeDIA and Cascadia reject it.',
    };
  }
  if (state.mode === 'pdc') {
    return {
      locked: true,
      reason: 'PDC mode requires DIA-NN — only DIA-NN is supported for PDC studies.',
    };
  }
  if (state.values['use_vendor_raw'] === true) {
    return {
      locked: true,
      reason:
        'You chose to feed vendor RAW directly. Only DIA-NN consumes vendor RAW without conversion.',
    };
  }
  if (quantSpectraKind(state.values['quant_spectra_dir']) === 'batch-map') {
    return {
      locked: true,
      reason:
        'Named-batch quant input runs as separate DIA-NN searches per batch — only DIA-NN supports this.',
    };
  }
  return { locked: false };
}

export function SearchEngineScreen() {
  const state = useFormState();
  const setValue = useStore((s) => s.setValue);
  const { value } = useFieldValue('search_engine');
  const current = readEngine(value);

  const lock = isLockedToDiann(state);

  // If locked and the current engine isn't DIA-NN, snap to DIA-NN so the
  // user can't proceed in an invalid state. (This also unblocks canAdvance.)
  useEffect(() => {
    if (lock.locked && current !== 'diann') {
      setValue('search_engine', 'diann');
    }
  }, [lock.locked, current, setValue]);

  const onChange = (next: Engine): void => {
    setValue('search_engine', next);
  };

  return (
    <div className="space-y-4">
      <p className="text-sm text-slate-600">
        Pick the search engine. Each one has different requirements for the
        background FASTA and spectral library.
      </p>
      {lock.locked ? (
        <div className="rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-[13px] text-amber-800">
          <span className="font-medium">DIA-NN required: </span>
          {lock.reason}
        </div>
      ) : null}
      <WizardRadioCards<Engine>
        ariaLabel="Search engine"
        value={current}
        onChange={onChange}
        options={[
          {
            value: 'diann',
            label: 'DIA-NN',
            description:
              'General-purpose, fast. Accepts vendor RAW directly. Can predict a library from FASTA or use one you provide.',
          },
          {
            value: 'encyclopedia',
            label: 'EncyclopeDIA',
            description:
              'Library-centric. Requires either a spectral library you provide or one generated by Carafe.',
            disabled: lock.locked,
          },
          {
            value: 'cascadia',
            label: 'Cascadia',
            description:
              'De novo. Generates its own FASTA; ignores spectral libraries. GPU-friendly.',
            disabled: lock.locked,
          },
        ]}
      />
      <Field path="images.diann" />
      <WizardAdvancedSection>
        <p className="text-[12px] text-slate-500">
          Engine-specific parameters appear when their engine is selected.
        </p>
        <Field path="diann.search_params" bypassTier />
        <Field path="diann.fasta_digest_params" bypassTier />
        <Field path="encyclopedia.quant.params" bypassTier />
        <Field path="encyclopedia.chromatogram.params" bypassTier />
        <Field path="encyclopedia.save_output" bypassTier />
        <Field path="cascadia.use_gpu" bypassTier />
        <Field path="cascadia.score_threshold" bypassTier />
      </WizardAdvancedSection>
    </div>
  );
}

export function searchEngineCanAdvance(state: FormState): boolean {
  return readEngine(state.values['search_engine']) !== null;
}
