// Types describing schema-derived parameter metadata. The concrete map of
// entries is generated by scripts/gen-param-metadata.ts and emitted to
// schemaDerived.generated.ts.

export type ScalarKind = 'string' | 'integer' | 'number' | 'boolean';

export type SchemaShape =
  | { kind: ScalarKind }
  | { kind: 'enum'; values: readonly string[] }
  | { kind: 'string-or-list' }
  | { kind: 'string-or-list-or-map' };

export interface SchemaDerivedEntry {
  readonly path: string;
  readonly shape: SchemaShape;
  readonly defaultValue: unknown;
  readonly hidden: boolean;
  readonly minimum?: number;
  readonly maximum?: number;
}

export type SchemaDerivedMap = Readonly<Record<string, SchemaDerivedEntry>>;
