// Header rendering and small indentation helpers.

export const INDENT = '    ';

export function indentLine(level: number, text: string): string {
  return INDENT.repeat(level) + text;
}

export function header(version: string, timestamp: Date): string {
  const iso = timestamp.toISOString();
  return [
    '// nf-skyline-dia-ms configuration',
    `// Generated by config-builder v${version} on ${iso}`,
    '// https://mriffle.github.io/nf-skyline-dia-ms-config-gui/',
    '',
  ].join('\n');
}
